### ISSUE TITLE
Alterar título na descrição do autor

### ISSUE THREAD

**Issue by froeder** [MarioDeAraujoCarvalho/EasyUploadPHP#1]
Título se ecnontra como DataCollectorWEB

**Comment by MarioCarvalhoBr** [comment]
Verdade, ainda estou terminando a documentação, mais vou corrigir o mais
rápido possível

Em seg, 12 de mar de 2018 15:14, Jhonatan Froeder <notifications@github.com>
escreveu:

**Comment by froeder** [comment]
Ok.
